# Generated by Django 3.1.5 on 2021-01-09 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solarsprint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_games_played', models.IntegerField(default=0)),
                ('unlocked_pr', models.BooleanField(default=True)),
                ('unlocked_arac', models.BooleanField(default=False)),
                ('unlocked_arth', models.BooleanField(default=False)),
                ('unlocked_arc', models.BooleanField(default=False)),
                ('high_score', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
